### ISSUE TITLE
anti-virus flags download for the zip file (see attached)

### ISSUE THREAD

**Issue by DeFiMoney-Printer** [ZooFarming/ZooGenes-3D-Assests#2]
![image](https://user-images.githubusercontent.com/81204298/225190165-543ef79a-35ff-4fd3-a68e-4ae30491c48a.png)

**Comment by DeFiMoney-Printer** [comment]
https://www.escape-technology.com/news/virus-found-in-maya-files an article that may be relevant to this from 2020

**Comment by iamcryptofennec** [comment]
Thanks for your report.

I just use my antivirus to disinfect .ma script to remove malicious code part.

![image](https://user-images.githubusercontent.com/128964/225215281-70631692-d04b-4d62-aba3-c5cb8e39686c.png)

And published a new zip here : https://github.com/ZooFarming/ZooGenes-3D-Assets/releases/tag/v1.0.1
